dev:
  sourceUrl: "localhost:27017"
  sourceDatabase: "DefaultDatabase"
  sourceUserNameArn: "sourceUsername"
  sourceUserPasswordArn: "sourcePassword"
  destinationUrl: "localhost:27018"
  destinationDatabase: "DefaultDatabase"
  destinationUserNameArn: "destUsername"
  destinationUserPasswordArn: "destPassword"
  validCollections:
    - "collectionOne"
    - "collectionTwo"
prod:
  sourceUrl: "mongodb://prod-source-server"
  sourceDatabase: "DefaultDatabase"
  sourceUserNameArn: "arn:aws:secretsmanager:prod:source:username"
  sourceUserPasswordArn: "arn:aws:secretsmanager:prod:source:password"
  destinationUrl: "mongodb://prod-destination-server"
  destinationDatabase: "prodDestinationDb"
  destinationUserNameArn: "arn:aws:secretsmanager:prod:destination:username"
  destinationUserPasswordArn: "arn:aws:secretsmanager:prod:destination:password"
  validCollections:
    - "collectionOne"
    - "collectionTwo"