local:
  databases:
    db_name1:
      sourceUrl: "localhost:27017"
      sourceUserNameArn: ""
      sourceUserPasswordArn: ""
      destinationUrl: "localhost:27018"
      destinationUserNameArn: ""
      destinationUserPasswordArn: ""
    db_name2:
      sourceUrl: "localhost:27017"
      sourceUserNameArn: ""
      sourceUserPasswordArn: ""
      destinationUrl: "localhost:27018"
      destinationUserNameArn: ""
      destinationUserPasswordArn: ""
dev:
  databases:
    db_name1:
      sourceUrl: "localhost:27017"
      sourceUserNameArn: ""
      sourceUserPasswordArn: ""
      destinationUrl: "localhost:27018"
      destinationUserNameArn: ""
      destinationUserPasswordArn: ""
    db_name2:
      sourceUrl: "localhost:27017"
      sourceUserNameArn: ""
      sourceUserPasswordArn: ""
      destinationUrl: "localhost:27018"
      destinationUserNameArn: ""
      destinationUserPasswordArn: ""
qa:
  databases:
    db_name1:
      sourceUrl: "localhost:27017"
      sourceUserNameArn: ""
      sourceUserPasswordArn: ""
      destinationUrl: "localhost:27018"
      destinationUserNameArn: ""
      destinationUserPasswordArn: ""
    db_name2:
      sourceUrl: "localhost:27017"
      sourceUserNameArn: ""
      sourceUserPasswordArn: ""
      destinationUrl: "localhost:27018"
      destinationUserNameArn: ""
      destinationUserPasswordArn: ""