dev:
  sourceUrl: "localhost:27017"
  sourceDatabase: "DefaultDatabase"
  sourceUserNameArn: "arn:aws:secretsmanager:us-east-1:000000000000:secret:sourceUsername-fUWLtW"
  sourceUserPasswordArn: "arn:aws:secretsmanager:us-east-1:000000000000:secret:sourcePassword-OKRKUt"
  destinationUrl: "localhost:27018"
  destinationDatabase: "DefaultDatabase"
  destinationUserNameArn: "arn:aws:secretsmanager:us-east-1:000000000000:secret:destUsername-xPBfqU"
  destinationUserPasswordArn: "arn:aws:secretsmanager:us-east-1:000000000000:secret:destPassword-trTUWu"
  validCollections:
    - "COLLECTION_ONE"
    - "COLLECTION_TWO"
    - "yourCollectionName"
qa:
  sourceUrl: "MongoSource:27017"
  sourceDatabase: "DefaultDatabase"
  sourceUserNameArn: "arn:aws:secretsmanager:us-east-1:000000000000:secret:sourceUsername-fUWLtW"
  sourceUserPasswordArn: "arn:aws:secretsmanager:us-east-1:000000000000:secret:sourcePassword-OKRKUt"
  destinationUrl: "MongoDestination:27017"
  destinationDatabase: "DefaultDatabase"
  destinationUserNameArn: "arn:aws:secretsmanager:us-east-1:000000000000:secret:destUsername-xPBfqU"
  destinationUserPasswordArn: "arn:aws:secretsmanager:us-east-1:000000000000:secret:destPassword-trTUWu"
  validCollections:
    - "COLLECTION_ONE"
    - "COLLECTION_TWO"
    - "yourCollectionName"
prod:
  sourceUrl: "mongodb://prod-source-server"
  sourceDatabase: "DefaultDatabase"
  sourceUserNameArn: "arn:aws:secretsmanager:prod:source:username"
  sourceUserPasswordArn: "arn:aws:secretsmanager:prod:source:password"
  destinationUrl: "mongodb://prod-destination-server"
  destinationDatabase: "prodDestinationDb"
  destinationUserNameArn: "arn:aws:secretsmanager:prod:destination:username"
  destinationUserPasswordArn: "arn:aws:secretsmanager:prod:destination:password"
  validCollections:
    - "COLLECTION_ONE"
    - "COLLECTION_TWO"
    - "yourCollectionName"